name: build

on:
  workflow_dispatch:
    inputs:
      package:
        description: package name
        required: false
        default: ""
        type: string
      command:
        description: command
        required: false
        default: ""
        type: string
      runner:
        description: runner
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-13

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/install-nix
      - uses: cachix/cachix-action@master
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: rm -f ~/.config/nix/nix.conf
      - if: ${{ inputs.package != '' }}
        run: |
          nix flake update
          nix-env -i nix-fast-build -f '<nixpkgs>'
          nix-fast-build --skip-cached --no-download --no-nom --flake ".#legacyPackages.$(nix eval --raw --impure --expr builtins.currentSystem).${{ inputs.package }}"
      - if: ${{ inputs.command != '' }}
        run: ${{ inputs.command }}
        # nix build --show-trace -L -v --impure github:NixOS/nixpkgs/master#librewolf
        # nix-shell maintainers/scripts/update.nix --argstr commit true --argstr package coreutils
