name: build-os

on:
  workflow_dispatch:

jobs:
  build-os:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/install-nix
      - uses: cachix/cachix-action@master
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: rm -f ~/.config/nix/nix.conf
      - run: |
          nix flake update
          nix-env -i nix-fast-build -f '<nixpkgs>'
          nix-fast-build --skip-cached --no-download --no-nom --flake ".#nixosConfigurations.noirriko.config.system.build.toplevel"
