name: debug

on:
  workflow_dispatch:
    inputs:
      runner:
        description: runner
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-13

jobs:
  debug:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/install-nix
      - uses: arduino/setup-task@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@master
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: rm -f ~/.config/nix/nix.conf
      - run: curl -sSf https://sshx.io/get | sh -s run
